config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: [:show]
  resources :years, except: [:index]
  resources :semesters
  get 'semesters/share/:share_token', to: 'semesters#share', as: :share_semester
  get 'semesters/import_form/:share_token', to: 'semesters#import_form', as: :import_form_semester
  post 'semesters/import/:share_token', to: 'semesters#import', as: :import_semester
  post 'import_redirect', to: 'semesters#import_redirect', as: :import_redirect_semester
  get 'upcoming_assessments', to: 'exams#upcoming_assessments', as: :all_upcoming_assessments
  resources :uni_modules do
    resources :exams do
      patch :mark_completed, on: :member
    end
    resources :timelogs

    member do
      patch :pin
    end
  end
  resources :exam_results, only: %i[create edit update]
  resources :uni_module_targets, only: %i[create update]

  get 'quick_log_form', to: 'pages#quick_log_form'
  post 'quick_log', to: 'pages#quick_log'
  get 'close_modal', to: 'pages#close_modal'

  scope :charts, controller: :charts do
    get :time_dashboard
    get 'time_year/:id',     action: :time_year,     as: :time_year
    get 'time_semester/:id', action: :time_semester, as: :time_semester
    get 'time_module/:id',   action: :time_module,   as: :time_module
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
  get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'

  get 'dashboard', to: 'pages#dashboard'

  # Fix for sign out bug
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end
# rubocop:enable Metrics/BlockLength

app/models/uni_module.rb
# frozen_string_literal: true

# rubocop:disable Rails/HasAndBelongsToMany
class UniModule < ApplicationRecord
  MAX_MODULES_PER_SEMESTER = 20

  has_and_belongs_to_many :semesters
  before_save :normalize_module_code
  after_commit :touch_semesters

  has_many :exams, dependent: :destroy
  has_many :timelogs, dependent: :destroy
  has_many :uni_module_targets, dependent: :destroy
  validate :semester_module_limit, on: :create

  def semester_module_limit
    return unless semesters.any? && semesters.first.uni_modules.count >= MAX_MODULES_PER_SEMESTER

    errors.add(:base, "You can only have up to #{MAX_MODULES_PER_SEMESTER} modules per semester.")
  end

  def normalize_module_code
    self.code = code.to_s.upcase
  end

  def credit_share
    credits.to_f / semesters.count
  end

  def total_minutes(since_string = 'all')
    since = TimelogGraphService.date_of(since_string)

    scope = timelogs
    scope = scope.where(date: since..) if since.present?

    scope.sum(:minutes)
  end

  def exams_with_results(user)
    exams.joins(:exam_results)
         .where(exam_results: { user_id: user.id })
         .where.not(exam_results: { score: nil })
  end

  def correct_weight_sum?
    exams.sum(:weight) == 100
  end

  def progress(user)
    exams_with_results(user).sum(:weight)
  end

  # Gets the average score of all of the completed exams so far, weighted by credits
  def weighted_average(user)
    valid_exams = exams_with_results(user)
    total_weight = valid_exams.sum(&:weight)
    weighted_sum = valid_exams.sum { |exam| exam.weight * exam.adjusted_score(user) }
    total_weight.zero? ? 0 : (weighted_sum / total_weight)
  end

  # Gets the score you have got so far, ie. the score you would get if you stopped now
  def achieved_score(user)
    valid_exams = exams_with_results(user)
    valid_exams.sum { |exam| exam.adjusted_score(user) * exam.weight / 100 }
  end

  # Gets the percentage completion of the module based on the exams taken
  def completion_percentage(user)
    return 0 unless exams.exists?

    exams_with_results(user).sum(:weight)
  end

  def target(user)
    target = UniModuleTarget.find_by(user: user, uni_module: self)
    return nil if target.nil? || target.score.nil?

    target.score
  end

  private

  def touch_semesters
    # Can't use touch_all as that does't trigger callbacks
    semesters.each(&:touch)
  end
end
# rubocop:enable Rails/HasAndBelongsToMany

app/controllers/uni_modules_controller.rb
# frozen_string_literal: true

class UniModulesController < ApplicationController
  before_action :set_uni_module, only: %i[show edit update destroy]
  authorize_resource

  # GET /uni_modules or /uni_modules.json
  def index
    @uni_modules = current_user.uni_modules

    return if params[:search].blank?

    query = "%#{params[:search]}%"
    @uni_modules = @uni_modules.where('LOWER(uni_modules.code) LIKE ? OR LOWER(uni_modules.name) LIKE ?',
                                      query.downcase, query.downcase)
  end

  # GET /uni_modules/1 or /uni_modules/1.json
  def show
    @exam_data = Exam
                 .where(uni_module: @uni_module)
                 .pluck(:name, :weight)
                 .to_h
    @timelogs = @uni_module.timelogs.for_user(current_user).order(date: :desc).page(params[:page]).per(5)
  end

  # GET /uni_modules/new
  def new
    @uni_module = UniModule.new(semester_ids: [params[:semester_id]])
  end

  # GET /uni_modules/1/edit
  def edit
    @uni_module_target = UniModuleTarget.find_by(uni_module: @uni_module,
                                                 user: current_user) || UniModuleTarget.new(
                                                   user: current_user, uni_module: @uni_module
                                                 )
  end

  # POST /uni_modules or /uni_modules.json
  def create
    @uni_module = UniModule.new(uni_module_params)

    respond_to do |format|
      if @uni_module.save
        format.html { redirect_to @uni_module, notice: 'Uni module was successfully created.' }
        format.json { render :show, status: :created, location: @uni_module }
      else
        format.html { render :new, status: :unprocessable_content }
        format.json { render json: @uni_module.errors, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /uni_modules/1 or /uni_modules/1.json
  def update
    respond_to do |format|
      if @uni_module.update(uni_module_params)
        format.html { redirect_to @uni_module, notice: 'Uni module was successfully updated.' }
        format.json { render :show, status: :ok, location: @uni_module }
      else
        format.html { render :edit, status: :unprocessable_content }
        format.json { render json: @uni_module.errors, status: :unprocessable_content }
      end
    end
  end

  # DELETE /uni_modules/1 or /uni_modules/1.json
  def destroy
    @uni_module.destroy!

    respond_to do |format|
      format.html { redirect_to uni_modules_path, status: :see_other, notice: 'Uni module was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pin
    @uni_module = UniModule.find(params[:id])
    if @uni_module.update(pinned: !@uni_module.pinned)
      redirect_to uni_module_path(@uni_module), notice: 'Module pin status updated successfully.'
    else
      redirect_to uni_module_path(@uni_module), alert: 'Failed to update pin status.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_uni_module
    @uni_module = UniModule.find(params[:id])

    @semester = @uni_module.semesters.first
  end

  # Only allow a list of trusted parameters through.
  def uni_module_params
    params.require(:uni_module).permit(:code, :name, :credits, :target, semester_ids: [])
  end
end

app/helpers/uni_modules_helper.rb
# frozen_string_literal: true

module UniModulesHelper
end

app/views/uni_modules/_exams.html.haml
.heading#assessments
  %h2 Assessments
  - unless @uni_module.correct_weight_sum?
    .icon-button.text-danger
      %i.fa-solid.fa-triangle-exclamation{ title: 'Total weight must be 100%' }
  .icon-button
    = link_to new_uni_module_exam_path(@uni_module), { title: 'Add Assessment' } do
      %i.fa-solid.fa-plus
.body
  - if @uni_module.exams.present?
    .link-cards-list
      - @uni_module.exams.each do |exam|
        = link_to uni_module_exam_path(@uni_module, exam) do
          .space-between
            .name= exam.name
            - if exam.score(current_user)
              .actual= "#{number_with_precision(exam.score(current_user), precision: 2)}%"
            - elsif exam.target(current_user)
              .required.text-muted= "Required: #{number_with_precision(exam.target(current_user), precision: 2)}%"
            - else 
              .empty.text-muted= "No Score"
          .space-between
            .font-secondary= exam.weight.to_s + '% Weighting'
            .font-secondary= exam.due&.strftime("%-d %b %Y")

app/views/uni_modules/_form.html.haml
.gt-form
  = form_for @uni_module do |f|
    - if @uni_module.errors.any?
      #error_explanation
        %h2= "#{pluralize(@uni_module.errors.count, "error")} prohibited this uni_module from being saved:"
        %ul
          - @uni_module.errors.full_messages.each do |message|
            %li= message
    .field
      = f.label :semester_ids, "Semesters"
      = f.collection_check_boxes :semester_ids, current_user.semesters, :id, :name do |b|
        .checkbox
          = b.check_box
          = "#{b.object.year.name} / #{b.object.name}"
    - if current_user.semesters.empty?
      %span.font-secondary.text-danger You currently have no semesters. Please create one under the relevant year to continue.
    .field
      = f.label :code
      = f.text_field :code
    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :credits
      = f.number_field :credits

    .actions
      = f.submit 'Save'

app/views/uni_modules/_target_form.haml
= form_for [@uni_module_target] do |f|
  = f.hidden_field :uni_module_id, value: @uni_module.id

  .field
    = f.label :score do
      Target
      %span.font-secondary= " (%)"
    = f.text_field :score

  .actions
    = f.submit 'Save'

app/views/uni_modules/_timelogs.html.haml
.gt-empty-card
  .heading
    %h2 Timelog
    .icon-button
      = link_to new_uni_module_timelog_path(@uni_module), title: 'Log time' do
        %i.fa-solid.fa-plus
  .body
    %table.gt-table.mt-0
      %thead
        %tr
          %th.px-2 Date
          %th.px-2 Minutes
          %th.px-2 Description
          %th

      %tbody
        - @timelogs.each do |timelog|
          %tr.timelog-row
            %td= timelog.created_at.strftime('%Y-%m-%d')
            %td= timelog.minutes
            %td= timelog.description
            %td.text-end
              .icon-button
                = link_to edit_uni_module_timelog_path(@uni_module, timelog) do
                  %i.fa-solid.fa-pen-to-square
    = paginate @timelogs

app/views/uni_modules/edit.html.haml
.form-card-container
  = link_to uni_module_path(@uni_module), class:'unstyle-link font-secondary mb-1' do
    %i.fa-solid.fa-arrow-left
    %span="Back to #{@uni_module.code}"

  .gt-empty-card
    .heading
      %h1 Editing Module

    .body
      = render 'form'

  .gt-card.gt-form#target-form
    = render 'target_form'

  .gt-card
    %h2= "Delete " + @uni_module.name 
    = button_to 'Delete', uni_module_path(@uni_module), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: 'link-button delete w-100'

app/views/uni_modules/index.html.haml
.gt-empty-card 
  .heading
    %h1 All Modules
    .gt-form
      = form_with url: uni_modules_path, method: :get, local: true do
        .form-row
          = text_field_tag :search, params[:search]
          = submit_tag "Search"

  .body
    .link-cards-list
      - @uni_modules.each do |uni_module|
        = link_to uni_module do
          .space-between 
            .name= uni_module.name
            .score= number_with_precision(uni_module.achieved_score(current_user), precision: 2) + '%'
          .space-between 
            .font-secondary= uni_module.code
            .font-secondary= uni_module.credits.to_s + ' Credits'

    = link_to '+ New Module', new_uni_module_path, class: 'card-button w-100 mt-2'

app/views/uni_modules/new.html.haml
.form-card-container
  .gt-empty-card
    .heading
      %h1 New Module

    .body
      = render 'form'

app/views/uni_modules/show.html.haml
.page-heading  
  %nav
    %ol.breadcrumb
      %li.breadcrumb-item= link_to @semester.year.name, @semester.year
      %li.breadcrumb-item= link_to @semester.name, @semester 
      %li.breadcrumb-item.active= @uni_module.name
  .button-row
    = button_to pin_uni_module_path(@uni_module), method: :patch, class: 'icon-button', title: (@uni_module.pinned? ? 'Unpin module' : 'Pin module') do
      - if @uni_module.pinned?
        .icon-button
          %i.fa-solid.fa-thumbtack
      - else
        .icon-button.unselected
          %i.fa-solid.fa-thumbtack
    .icon-button
      = link_to edit_uni_module_path(@uni_module) do
        %i.fa-solid.fa-pen-to-square

-# Stats
.stats-container 
  .stat 
    .stat-header Credits
    .stat-content= number_with_precision(@uni_module.credits, precision: 0)
  .stat 
    .stat-header Weighted Average
    .stat-content= number_with_precision(@uni_module.weighted_average(current_user), precision: 2) + '%'
  .stat 
    .stat-header Achieved Score
    .stat-content= number_with_precision(@uni_module.achieved_score(current_user), precision: 2) + '%'

.exams-container
  .exams 
    .gt-empty-card
      = render 'exams'
  .graph-split
    .gt-empty-card
      .heading
        %h2 Assessment Split
      .body
        .chart-container
          = pie_chart @exam_data, legend: false, width: "100%", library: { aspectRatio: "1|1" }, id: 'exam-chart'

-# Graph
= turbo_frame_tag "uni_module_time_chart" do
  = render partial: 'shared/time_chart', locals: { subject: @uni_module, time_path: -> { time_module_path(id: @uni_module.id, cumulative: params[:cumulative], date_since: params[:date_since]) }, date_since: params[:date_since], form_url: uni_module_path(@uni_module), turbo_frame_id: "uni_module_time_chart" }
      
.row
  .col
    = render 'timelogs'