config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: [:show]
  resources :years, except: [:index]
  resources :semesters
  get 'semesters/share/:share_token', to: 'semesters#share', as: :share_semester
  get 'semesters/import_form/:share_token', to: 'semesters#import_form', as: :import_form_semester
  post 'semesters/import/:share_token', to: 'semesters#import', as: :import_semester
  post 'import_redirect', to: 'semesters#import_redirect', as: :import_redirect_semester
  get 'upcoming_assessments', to: 'exams#upcoming_assessments', as: :all_upcoming_assessments
  resources :uni_modules do
    resources :exams do
      patch :mark_completed, on: :member
    end
    resources :timelogs

    member do
      patch :pin
    end
  end
  resources :exam_results, only: %i[create edit update]
  resources :uni_module_targets, only: %i[create update]

  get 'quick_log_form', to: 'pages#quick_log_form'
  post 'quick_log', to: 'pages#quick_log'
  get 'close_modal', to: 'pages#close_modal'

  scope :charts, controller: :charts do
    get :time_dashboard
    get 'time_year/:id',     action: :time_year,     as: :time_year
    get 'time_semester/:id', action: :time_semester, as: :time_semester
    get 'time_module/:id',   action: :time_module,   as: :time_module
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
  get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'

  get 'dashboard', to: 'pages#dashboard'

  # Fix for sign out bug
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end
# rubocop:enable Metrics/BlockLength

app/views/shared/_dashboard_stats.html.haml
- cache [current_user] do  
  .stats-container 
    .stat 
      .stat-header Module Count
      .stat-content= link_to current_user.uni_modules.count, uni_modules_path
    .stat 
      .stat-header Average Score
      .stat-content= number_with_precision(current_user.average_score, precision: 2) + '%'
    .stat 
      .stat-header Achieved Score
      .stat-content= number_with_precision(current_user.achieved_score, precision: 2) + '%'
    .stat 
      .stat-header Exams
      .stat-content= current_user.exams.count

app/views/shared/_exam_card.html.haml
= link_to uni_module_exam_path(exam.uni_module, exam) do
  .name-row
    .text-truncate= exam.name
    .mod-code= exam.uni_module.code
  - if exam.due
    .date-row
      .due-date.font-secondary
        Due:
        = exam.due.strftime("%d %b %Y, %H:%M")
      - if exam.due < Time.current
        - if exam.completed
          .chip-success= "Completed"
      - elsif exam.due < 1.day.from_now
        .chip-danger= "#{((exam.due - Time.current)/1.hour).floor} Hours"
      - elsif exam.due < 1.week.from_now
        .chip-warning= "#{(exam.due.to_date - Date.today).to_i} Days"

app/views/shared/_modal_wrapper.html.haml
= turbo_frame_tag "modal" do
  .modal.fade.show.d-block{ tabindex: "-2", role: "dialog", aria: { modal: "true" } }
    .modal-dialog.modal-md.modal-dialog-centered
      .modal-content.gt-modal
        .modal-header
          %h5.modal-title= title
          = link_to close_modal_path, class: "icon-button", aria: { label: "Close" }, data: { turbo_frame: "_top" } do
            %i.fa-solid.fa-x

        .modal-body
          = yield

  = link_to "",
    close_modal_path,
    class: "modal-backdrop fade show",
    aria: { label: "Close" },
    data: { turbo_frame: "_top" }

app/views/shared/_module_card.html.haml
- cache [uni_module.semesters.first, uni_module, current_user] do  
  = link_to uni_module_path(uni_module) do
    - progress = uni_module.progress(current_user)
    - achieved_score = uni_module.achieved_score(current_user)
    .space-between
      .space-between
        .name= uni_module.code + " - " + uni_module.name
        - if progress == 100
          = class_badge(achieved_score)
      .actual= "#{number_with_precision(achieved_score, precision: 0)}%"
    .space-between
      .font-secondary= "#{uni_module.credits.present? ? number_with_precision(uni_module.credits, precision: 0) : "N/A"} Credits"
      .font-secondary= "#{number_with_precision(progress, precision: 0)}% Completed"

app/views/shared/_semester_card.html.haml
  
- cache [semester, current_user] do   
  = link_to semester_path(semester) do
    - progress = semester.progress(current_user)
    - achieved_score = semester.achieved_score(current_user)
    .space-between
      .space-between
        .name= semester.name
        - if progress == 100
          = class_badge(achieved_score)
      .actual= "#{number_with_precision(achieved_score, precision: 0)}%"
    .space-between
      .font-secondary= "#{number_with_precision(semester.credits, precision: 0)} Credits"
      .font-secondary= "#{number_with_precision(progress, precision: 0)}% Completed"

app/views/shared/_time_chart.html.haml
.gt-empty-card#chart_card
  .heading
    .mini-stat
      .title Minutes Spent
      .figure= subject.total_minutes(date_since)

    - form_url = local_assigns[:form_url].presence || request.path
    - turbo_frame_id = local_assigns[:turbo_frame_id]
    - form_data = turbo_frame_id.present? ? { turbo_frame: turbo_frame_id } : {}
    = form_with url: form_url,
                method: :get,
                data: form_data.merge(turbo: true),
                html: { class: "gt-form cumulative-toggle-form", action: form_url } do |f|
      .split-row.mobile-col
        = f.select :date_since,
            [ ["All Time", "all"],
              ["Last Week", "1_week"],
              ["Last Month", "1_month"],
              ["Last 3 Months", "3_months"],
              ["Last 6 Months", "6_months"]],
            { selected: params[:date_since] || "all" },
            { onchange: "this.form.requestSubmit()", class: "cumulative-dropdown text-muted" }
        = f.select :cumulative,
            [["Cumulative", "true"], ["Daily", "false"]],
            { selected: params[:cumulative] || "true" },
            { onchange: "this.form.requestSubmit()", class: "cumulative-dropdown text-muted" }

  .body
    .chart-container
      - if params[:cumulative] == "false"
        = column_chart time_path.call, stacked: true, zeros: false, legend: false, width: "100%", height: "300px", library: { responsive: true, maintainAspectRatio: false, scales: { x: { type: "time", time: { unit: "day", displayFormats: { day: "MMM d" }, tooltipFormat: "MMM d" } } }, animation: {duration: 1000, easing: "easeOutQuart"} }
      - else 
        = line_chart time_path.call, 
          curve: false, 
          legend: false, 
          width: "100%", 
          height:"300px", 
          library: { responsive: true, maintainAspectRatio: false }

app/views/shared/_year_card.html.haml
- cache [year, current_user] do   
  = link_to year_path(year) do
    - progress = year.progress(current_user)
    - achieved_score = year.achieved_score(current_user)
    .space-between
      .space-between
        .name= year.name
        - if progress == 100
          = class_badge(achieved_score)
      .actual= "#{number_with_precision(achieved_score, precision: 0)}%"
    .space-between
      .font-secondary= "#{number_with_precision(year.weighting, precision: 0)}% Weighting"
      .font-secondary= "#{number_with_precision(progress, precision: 0)}% Completed"